"""add fcm push subscriptions and notifications

Revision ID: 40775e63270f
Revises: a1c5f0e2b7d4
Create Date: 2026-08-17 08:25:13.214142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40775e63270f'
down_revision = 'a1c5f0e2b7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_dedupes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'subject_id', name='uq_notification_dedupe')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('events_new', sa.Boolean(), nullable=False),
    sa.Column('events_reminders', sa.Boolean(), nullable=False),
    sa.Column('bethak_opens', sa.Boolean(), nullable=False),
    sa.Column('literary_new_publications', sa.Boolean(), nullable=False),
    sa.Column('literary_editors_picks', sa.Boolean(), nullable=False),
    sa.Column('activity_submission_approved', sa.Boolean(), nullable=False),
    sa.Column('activity_submission_rejected', sa.Boolean(), nullable=False),
    sa.Column('activity_changes_requested', sa.Boolean(), nullable=False),
    sa.Column('community_comments', sa.Boolean(), nullable=False),
    sa.Column('system_announcements', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=500), nullable=False),
    sa.Column('browser', sa.String(length=60), nullable=True),
    sa.Column('device', sa.String(length=60), nullable=True),
    sa.Column('platform', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_fcm_token'), ['fcm_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('bethak_session_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bethak_session_id'], ['bethak_sessions.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_fcm_token'))

    op.drop_table('push_subscriptions')
    op.drop_table('notification_preferences')
    op.drop_table('notification_dedupes')
    # ### end Alembic commands ###
