"""roles, themes, profiles, content review workflow

Revision ID: 7489d27a86dc
Revises: eb641b965beb
Create Date: 2026-08-02 12:33:08.171712

"""
import re

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7489d27a86dc'
down_revision = 'eb641b965beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=20), nullable=False,
                                       server_default='other'))
        # Existing posts predate the editorial workflow — treat them as
        # already-approved so they remain publicly visible after upgrade.
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=False,
                                       server_default='approved'))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_posts_reviewed_by_id_users', 'users', ['reviewed_by_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=30), nullable=False,
                                       server_default='classic-light'))
        # Any account that was still 'pending' under the old registration-approval
        # flow is auto-approved now that sign-up no longer requires review.
        batch_op.execute("UPDATE users SET status = 'approved' WHERE status = 'pending'")
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # Backfill a username for every pre-existing user (derived from their email).
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, email FROM users WHERE username IS NULL")).fetchall()
    used = set()
    for row in rows:
        base = re.sub(r"[^a-z0-9]+", "-", row.email.split("@")[0].lower()).strip("-") or "member"
        base = base[:40]
        candidate = base
        n = 1
        while candidate in used:
            n += 1
            candidate = f"{base}-{n}"
        used.add(candidate)
        conn.execute(
            sa.text("UPDATE users SET username = :username WHERE id = :id"),
            {"username": candidate, "id": row.id},
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('theme')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('interests')
        batch_op.drop_column('bio')
        batch_op.drop_column('username')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_reviewed_by_id_users', type_='foreignkey')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('review_status')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
