"""add postgres image storage (stored_images) and FK columns on events / weekly_highlights

Revision ID: f8b6520123e5
Revises: 40775e63270f
Create Date: 2026-08-17 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b6520123e5'
down_revision = '40775e63270f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'stored_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('mimetype', sa.String(length=100), nullable=False),
        sa.Column('data', sa.LargeBinary(), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=True),
        sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_events_cover_image_id_stored_images',
            'stored_images', ['cover_image_id'], ['id'],
        )
        # cover_image (the old filesystem-path column) is untouched here —
        # it was already nullable, and the app no longer reads/writes it.

    with op.batch_alter_table('weekly_highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_weekly_highlights_image_id_stored_images',
            'stored_images', ['image_id'], ['id'],
        )
        # image_path (the old filesystem-path column) was NOT NULL. The app
        # no longer writes to it, so it must be relaxed or every future
        # insert would fail. The column and any existing values are kept
        # in place (untouched) for scripts/migrate_legacy_images.py to read.
        batch_op.alter_column(
            'image_path', existing_type=sa.String(length=300), nullable=True,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_highlights', schema=None) as batch_op:
        batch_op.alter_column(
            'image_path', existing_type=sa.String(length=300), nullable=False,
        )
        batch_op.drop_constraint('fk_weekly_highlights_image_id_stored_images', type_='foreignkey')
        batch_op.drop_column('image_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_cover_image_id_stored_images', type_='foreignkey')
        batch_op.drop_column('cover_image_id')

    op.drop_table('stored_images')
    # ### end Alembic commands ###
